
kind: "ApplicationV1"
metadata:
  name: "whatsapp-bot-php"
  namespace: "your-username"

spec:
  package:
    name: "whatsapp-bot-php"
    registry: "wasmer.io"
    version: "1.0.0"
  
  env:
    - name: "PORT"
      value: "8080"
    - name: "NODE_ENV"
      value: "production"
  
  # Enable persistent workload for bot daemon
  capabilities:
    - instaboot