# ⚠️ WARNING: Ini format yang BENAR untuk Wasmer Edge
# TAPI bot WhatsApp TIDAK AKAN BERFUNGSI di Wasmer karena:
# 1. Bot butuh persistent WebSocket connection
# 2. Wasmer Edge adalah stateless platform (request-response)
# 3. Auth state akan hilang setiap restart
# 4. Node.js process tidak bisa run 24/7

kind: wasmer.io/App.v0
name: whatsapp-bot-php
owner: yrteam
package: .

# Environment variables
env:
  NODE_ENV: production
  PORT: "8080"

# CLI arguments untuk PHP
cli_args:
  - "-t"
  - "/app"
  - "-S"
  - "0.0.0.0:8080"

# Scaling mode
scaling:
  mode: single_concurrency

# Capabilities - INI FORMAT YANG BENAR
capabilities:
  instaboot:
    requests:
      - path: /
        method: GET

# Health checks (optional)
health_checks:
  - http:
      method: get
      path: /
      interval: 30s
      timeout: 10s
      unhealthy_threshold: 2
      healthy_threshold: 1
      expected_status_codes:
        - 200

# Debug mode
debug: true
